apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: vantage6-server
spec:
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        ports:
        - containerPort: 5672
        - containerPort: 15672
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: rabbitmquser
        - name: RABBITMQ_DEFAULT_PASS
          value: rabbitmquserpassword
        - name: RABBITMQ_DEFAULT_VHOST
          value: /vantage6
        # resources:
        #   limits:
        #     memory: "512Mi"
        #     cpu: "500m"
        #   requests:
        #     memory: "256Mi"
        #     cpu: "250m"