apiVersion: v1
kind: PersistentVolume
metadata:
  name: store-postgres-pv
  namespace: vantage6-server
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: "/mnt/data/"