# Policy to disable job's networking, except with the Node
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: vantage6-node-allow-egress-to-node-proxy-only
  namespace: vantage6-node
spec:
  podSelector: {} # This selects all pods in the vantage6-node namespace
  policyTypes:
  - Egress
  egress:
  - {}