apiVersion: v2
name: auth
description: A Helm chart to deploy a keycloak instance to authenticate vantage6 users and nodes
type: application
version: "5.0.0-rc6"
appVersion: "5.0.0-rc6"
dependencies:
  - name: common
    version: "5.0.0-rc6"
    repository: file://../common
