apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-vantage6-frontend-service
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  selector:
{{ include "vantage6.matchLabels" . | indent 4 }}
    component: ui
  ports:
    - protocol: TCP
      port: {{ .Values.ui.port }}   # External port for the UI
      targetPort: 4200    # Container port for the UI
      name: vantage6-server-frontend
  type: LoadBalancer