target-version = "py310"
line-length = 88          # Same as Black

[lint]
extend-select = ["I"]     # Enable linting for imports

[lint.isort]
known-first-party = ["vantage6"]
known-third-party = ["docker"]
force-single-line = false
combine-as-imports = true
section-order = ["future", "standard-library", "third-party", "v6-common", "first-party", "local-folder"]

[lint.isort.sections]
v6-common = ["vantage6.common"]