services:

  vantage6-server:
    image: harbor2.vantage6.ai/infrastructure/server:latest
    ports:
      - "7601:7601"
    depends_on:
      - database
    volumes:
      - ./configs/postgress.yaml:/mnt/config.yaml
    command: [
      "uwsgi",
      "--http", ":7601",
      "--gevent", "1000",
      "--http-websockets",
      "--http-chunked-input",
      "--http-keepalive",
      "--post-buffering", "0",
      "--master",
      "--callable", "app",
      "--disable-logging",
      "--wsgi-file", "/vantage6/vantage6-server/vantage6/server/wsgi.py",
      "--pyargv", "/mnt/config.yaml"
    ]

  database:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_PASSWORD: changeme