FROM python:3

ADD ./master_container.py /app/master_container.py
ADD ./slave_container.py /app/slave_container.py

RUN pip install docker
RUN pip install colorama

# RUN apt-get update && apt-get install -y docker-engine

RUN ls -lha /var/run

CMD [ "python", "/app/master_container.py" ]
# CMD [ "python", "/app/slave_container.py" ]