# TODO v5+ this nameOverride is required to be present, otherwise the server will
# not work (tested with v6 dev start). It should not be required
nameOverride: vantage6-server
server:
  description: Vantage6 server version 5

  baseUrl: http://localhost:7601
  apiPath: /server
  image: harbor2.vantage6.ai/infrastructure/server:latest

  keycloakUrl: http://vantage6-auth-keycloak.vantage6.svc.cluster.local
  keycloakRealm: vantage6
  keycloakAdminUsername: admin
  keycloakAdminPassword: admin
  keycloakAdminClient: backend-admin-client
  keycloakAdminClientSecret: myadminclientsecret
  keycloak:
    manage_users_and_nodes: true

  port: 7601
  internal:
    port: 7601

  replications: 1

  logging:
    level: DEBUG
    file: server.log
    max_size: 1024
    use_console: true
    datefmt: "%Y-%m-%d %H:%M:%S"
    format: "%(asctime)s - %(name)-14s - %(levelname)-8s - %(message)s"
    backup_count: 5
    loggers:
    - level: warning
      name: urllib3
    - level: warning
      name: socketIO-client
    - level: warning
      name: socketio.server
    - level: warning
      name: engineio.server
    - level: warning
      name: sqlalchemy.engine

  prometheus:
    enabled: false

rabbitmq:
  image:
    repository: rabbitmq
    tag: 3-management

  username: rabbitmquser
  password: rabbitmquserpassword
  vhost: /vantage6

database:
  external: false
  image:
    repository: postgres
    tag: 13
  username: vantage6
  password: vantage6
  name: vantage6
  volumePath: /mnt/data_server
  k8sNodeName: docker-desktop

ui:
  image: harbor2.vantage6.ai/infrastructure/ui:latest
  port: 7600

  keycloakRealm: vantage6
  keycloakClient: public_client
  keycloakPublicUrl: http://localhost:8080

  allowedAlgorithmStores: "*"
  communityStoreUrl: https://store.cotopaxi.vantage6.ai
  communityStoreApiPath: /api