# Override the chart name
nameOverride: vantage6-server
# Optional, by default the Release.Namespace is used
# namespace: vantage6-server
server:
  # The description of the server
  description: Vantage6 server version 5

  # The external URL of the server
  baseUrl: http://localhost:7601
  apiPath: /server

  # Keycloak configuration
  keycloakUrl: http://vantage6-auth-keycloak.vantage6.svc.cluster.local
  keycloakRealm: vantage6
  keycloakAdminUsername: admin
  keycloakAdminPassword: admin
  keycloakAdminClient: backend-admin-client
  keycloakAdminClientSecret: myadminclientsecret
  keycloak:
    manage_users_and_nodes: true

  internal:
    port: 7601

  port: 7601

  # The number of replicas of the server
  replications: 1

  # In production it is recommended to use a database that is not inside the k8s
  # cluster. By default, a postgres database is created inside the k8s cluster.
  # If you want to use an external database, you can set the database_uri here.
  # database_uri: postgresql://user:password@localhost:5432/mydatabase

  # In production it is recommended to use an external RabbitMQ server (outside
  # of k8s). By default, a RabbitMQ server is created inside the k8s cluster.
  # If you want to use an external RabbitMQ server, you can set the rabbitmq_uri
  # here.
  # rabbitmq_uri: amqp://user:password@localhost:5672/myvhost

  # The image of the server
  image: harbor2.vantage6.ai/infrastructure/server:latest

  logging:
    level: INFO
    file: server.log
    max_size: 1024
    use_console: true
    datefmt: "%Y-%m-%d %H:%M:%S"
    format: "%(asctime)s - %(name)-14s - %(levelname)-8s - %(message)s"
    backup_count: 5
    loggers:
    - level: warning
      name: urllib3
    - level: warning
      name: socketIO-client
    - level: warning
      name: socketio.server
    - level: warning
      name: engineio.server
    - level: warning
      name: sqlalchemy.engine
    - level: warning
      name: requests_oauthlib.oauth2_session

  # In case you want to use a static secret key for the JWT token. Setting this is not
  # recommended for production environments.
  # jwt:
  #   secret: "super-secret-key-that-you-shouldnt-use-in-production"

  dev:
    host_uri: host.docker.internal
    drop_all: 'True'

  # If you want to couple algorithm stores to the server on startup, you can add them here.
  # The name is used to identify the algorithm store in the server's database.
  # The url is the URL of the algorithm store's API.
  # algorithm_stores:
  #   - name: local store
  #     url: http://localhost:7602/api

rabbitmq:
  # The image of the RabbitMQ server
  image:
    repository: rabbitmq
    tag: 3-management

  # The username of the RabbitMQ server
  username: rabbitmquser

  # The password of the RabbitMQ server
  password: rabbitmquserpassword

  # The vhost of the RabbitMQ server
  vhost: /vantage6

database:
  # The image of the database
  image:
    repository: postgres
    tag: 13

  # The username of the database
  username: vantage6

  # The password of the database
  password: vantage6

  # The name of the database
  name: vantage6

  #hostpath of the database mount
  volumePath: /mnt/data_server

  # The name of the k8s node where the database is running
  k8sNodeName: docker-desktop

ui:

  # The image of the UI
  image: harbor2.vantage6.ai/infrastructure/ui:latest
  # Service port for the UI
  port: 7600
  # keycloak client
  keycloakClient: public_client
  # keycloak public URL
  keycloakPublicUrl: http://localhost:7680