apiVersion: v2
name: hub
description: A Helm chart to deploy the complete vantage6 hub (HQ, auth, algorithm store)
type: application
version: "5.0.0-b4"
appVersion: "5.0.0-b4"
dependencies:
  - name: hq
    version: "5.0.0-b4"
    repository: file://../hq
    condition: hq.enabled
  - name: auth
    version: "5.0.0-b4"
    repository: file://../auth
    condition: auth.enabled
  - name: store
    version: "5.0.0-b4"
    repository: file://../store
    condition: store.enabled
  - name: common
    version: "5.0.0-b4"
    repository: file://../common
