logging:
    level: CRITICAL
    file: unittest.log
    use_console: false
    backup_count: 5
    max_size: 1024
    format: "%(asctime)s - %(name)-14s - %(levelname)-8s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"