apiVersion: v1
kind: Service
metadata:
  name: vantage6-server-frontend-service
  namespace: vantage6-server
spec:
  selector:
    app: vantage6-server-frontend
  ports:
    - protocol: TCP
      port: 80          # External port for the UI
      targetPort: 80    # Container port for the UI
      name: vantage6-server-frontend
  type: ClusterIP