apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-store-configmap
  namespace: {{ .Values.namespace | default .Release.Namespace }}
data:
  config.yaml: |
    allow_drop_all: 'True'
    api_path: /store
    description: 'Vantage store version 5'
    ip: 0.0.0.0
    logging:
      backup_count: 5
      datefmt: '%Y-%m-%d %H:%M:%S'
      file: k8s.log
      format: '%(asctime)s - %(name)-14s - %(levelname)-8s - %(message)s'
      level: DEBUG
      loggers:
      - level: warning
        name: urllib3
      - level: warning
        name: socketIO-client
      - level: warning
        name: socketio.server
      - level: warning
        name: engineio.server
      - level: warning
        name: sqlalchemy.engine
      - level: warning
        name: requests_oauthlib.oauth2_session
      max_size: 1024
      use_console: true
    policies:
      algorithm_view: {{ .Values.store.policies.algorithmView }}
      allow_localhost: {{ .Values.store.policies.allowLocalhost }}
      allowed_servers:
      - "http://localhost:7601/server"
      min_reviewers: {{ .Values.store.policies.minReviewers }}
      min_reviewing_organizations: {{ .Values.store.policies.minReviewingOrganizations }}
      assign_review_own_algorithm: {{ .Values.store.policies.assignReviewOwnAlgorithm }}
    dev:
      host_uri: {{ .Values.store.dev.host_uri }}
      disable_review: {{ .Values.store.policies.dev.disable_review }}
      review_own_algorithm: {{ .Values.store.policies.dev.review_own_algorithm }}
    port: {{ .Values.store.internal.port }}
    root_user:
      username: {{ .Values.store.vantage6Server.rootUser }}
      v6_server_uri: {{ .Values.store.vantage6Server.uri }}
    uri: postgresql://{{ .Values.database.username }}:{{ .Values.database.password }}@{{ .Release.Name }}-postgres-service:5432/{{ .Values.database.name }}