apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-store-configmap
  namespace: {{ .Values.namespace | default .Release.Namespace }}
data:
  config.yaml: |
    api_path: {{ .Values.store.api_path }}
    description: {{ .Values.store.description }}
    {{- if .Values.database.external }}
    uri: {{ .Values.database.uri }}
    {{- else }}
    uri: postgresql://{{ .Values.database.username }}:{{ .Values.database.password }}@{{ .Release.Name }}-postgres-service:5432/{{ .Values.database.name }}
    {{- end }}
    logging:
      backup_count: {{ .Values.store.logging.backup_count }}
      datefmt: {{ .Values.store.logging.datefmt | quote }}
      file: {{ .Values.store.logging.file }}
      format: {{ .Values.store.logging.format | quote }}
      level: {{ .Values.store.logging.level }}
      loggers:
      {{- range .Values.store.logging.loggers }}
      - level: {{ .level }}
        name: {{ .name }}
      {{- end }}
      max_size: {{ .Values.store.logging.max_size }}
      use_console: {{ .Values.store.logging.use_console }}
    {{- if .Values.store.policies }}
    policies:
      {{- if .Values.store.policies.algorithmView }}
      algorithm_view: {{ .Values.store.policies.algorithmView }}
      {{- end }}
      {{- if .Values.store.policies.minReviewers }}
      min_reviewers: {{ .Values.store.policies.minReviewers }}
      {{- end }}
      {{- if .Values.store.policies.minReviewingOrganizations }}
      min_reviewing_organizations: {{ .Values.store.policies.minReviewingOrganizations }}
      {{- end }}
      {{- if .Values.store.policies.assignReviewOwnAlgorithm }}
      assign_review_own_algorithm: {{ .Values.store.policies.assignReviewOwnAlgorithm }}
      {{- end }}
      {{- if .Values.store.policies.allowedReviewers }}
      allowed_reviewers:
        {{- range .Values.store.policies.allowedReviewers }}
        - {{ . }}
        {{- end }}
      {{- end }}
      {{- if .Values.store.policies.allowedReviewAssigners }}
      allowed_review_assigners:
        {{- range .Values.store.policies.allowedReviewAssigners }}
        - {{ . }}
        {{- end }}
      {{- end }}
    {{- end }}
    {{- if .Values.store.cors_allowed_origins }}
    cors_allowed_origins:
      {{- range .Values.store.cors_allowed_origins }}
      - {{ . }}
      {{- end }}
    {{- end }}
    {{- if .Values.store.dev }}
    dev:
      host_uri: {{ .Values.store.dev.host_uri }}
      disable_review: {{ .Values.store.dev.disable_review }}
      review_own_algorithm: {{ .Values.store.dev.review_own_algorithm }}
    {{- end }}
    port: {{ .Values.store.internal.port }}
    root_user:
      username: {{ .Values.store.keycloakAdminUsername }}
      v6_server_uri: {{ .Values.store.vantage6ServerUri }}