apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-vantage6-server-config
  namespace: {{ .Release.Namespace | quote }}
data:
  config.yaml: |
    algorithm_stores: []
    allow_drop_all: 'True'
    api_path: /api
    description: Vantage6 server version 5
    ip: 0.0.0.0
    {{- if .Values.server.jwt.secret }}
    jwt_secret_key: {{ .Values.server.jwt.secret }}
    {{- end }}
    logging:
      backup_count: 5
      datefmt: '%Y-%m-%d %H:%M:%S'
      file: five.log
      format: '%(asctime)s - %(name)-14s - %(levelname)-8s - %(message)s'
      level: {{ .Values.server.logging.level }}
      loggers:
      - level: warning
        name: urllib3
      - level: warning
        name: socketIO-client
      - level: warning
        name: socketio.server
      - level: warning
        name: engineio.server
      - level: warning
        name: sqlalchemy.engine
      - level: warning
        name: requests_oauthlib.oauth2_session
      max_size: 1024
      use_console: true
    port: {{ .Values.server.internal.port }}
    server_url: {{ .Values.server.url }}
    uri: postgresql://{{ .Values.database.username }}:{{ .Values.database.password }}@{{ .Release.Name }}-postgres-service:5432/{{ .Values.database.name }}
    rabbitmq:
      uri: amqp://{{ .Values.rabbitmq.username }}:{{ .Values.rabbitmq.password }}@{{ .Release.Name }}-rabbitmq-service:5672/{{ .Values.rabbitmq.vhost }}
      start_with_server: false
    dev:
      host_uri: host.docker.internal