apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-node-create-algorithm-role
  labels:
{{- include "node.labels" . | nindent 4 }}
rules:
# The core permission needed since vantage6 node runs all algorithms as Kubernetes Jobs.
# Needs full management capabilities (create/delete) and monitoring capabilities
# (get/list/watch) to track job status and completion.
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "delete", "get", "list", "watch"]

# The vantage6 node needs permissions to manage pods and access their logs to monitor
# algorithm execution, collect results, and handle any issues that arise during task
# processing
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["create", "delete", "get", "list", "watch"]

# Algorithms might need persistent storage to store temporary or output data.
# The node needs to manage persistent volume claims (PVCs) to provide this storage
# to algorithm containers.
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["create", "delete", "get", "list"]

# Some algorithms might need network services for communication between components.
# The node needs to be able to create and manage these services for algorithm networking requirements.
- apiGroups: [""]
  resources: ["services"]
  verbs: ["create", "delete", "get", "list"]

# The node needs to be able to create and manage namespaces for task isolation.
# This is used by the ensure_task_namespace() method.
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["create", "get", "list"]