{{- range .Values.node.databases.fileBased }}
{{- $pvName := include "node.databasePvName" (dict "releaseName" $.Release.Name "databaseName" .name) }}
{{- if not (lookup "v1" "PersistentVolume" "" $pvName) }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $pvName }}
  labels:
    type: local-database
    database: {{ .name | quote }}
spec:
  capacity:
    storage: {{ $.Values.node.persistence.database.size }}
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ $.Values.node.persistence.database.storageClass }}
  persistentVolumeReclaimPolicy: Delete
  local:
    path: {{ .volumePath | quote }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - {{ $.Values.node.k8sNodeName }}
{{- end }}
{{- end }}
