{{- if .Values.node.createSecrets }}
  {{- $databaseNames := list }}
  {{- range $db := concat .Values.node.databases.fileBased .Values.node.databases.serviceBased }}
  {{- $databaseNames = append $databaseNames $db.name }}
  {{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Values.namespace | default .Release.Namespace }}
data:
  V6_API_KEY: {{ .Values.node.apiKey | b64enc }}
  V6_NODE_NAME: {{ .Values.node.name | b64enc }}
  DATABASE_LABELS: {{ join "," $databaseNames | b64enc }}
  {{- range $db := concat .Values.node.databases.fileBased .Values.node.databases.serviceBased }}
  {{- $envLabel := include "node.databaseEnvLabel" (dict "databaseName" $db.name) }}
  DATABASE_{{ $envLabel }}_URI: {{ $db.uri | b64enc }}
  DATABASE_{{ $envLabel }}_TYPE: {{ $db.type | b64enc }}
  {{- if $db.env }}
  {{- range $key, $value := $db.env }}
  DATABASE_{{ $envLabel }}_{{ $key | upper }}: {{ $value | b64enc }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- end }}