apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-vantage6-node-task-pv
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    type: local-tasks
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: {{ .Values.node.taskDirHost }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - {{ .Values.node.k8sNodeName }}