apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-node-service
  namespace: {{ .Release.Namespace | quote }}
spec:
  selector:
{{ include "node.matchLabels" . | indent 4 }}
    component: node
  ports:
  - protocol: TCP
    port:  {{ .Values.node.proxyPort }}
    targetPort:  {{ .Values.node.proxyPort }}