apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-node-service
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  selector:
{{ include "node.matchLabels" . | indent 4 }}
    component: node
  ports:
  # If numberOfNodes and and nodeProxyStartingPortNumber, a dev environment (devspace)
  # and multiple ports must be enabled
{{- if and (hasKey .Values.node "numberOfNodes") (hasKey .Values.node "nodeProxyStartingPortNumber") }}
  {{- $start := int .Values.node.nodeProxyStartingPortNumber }}
  {{- $count := int .Values.node.numberOfNodes }}
  {{- range $i, $ := until $count }}
    - name: {{ printf "node%d" (add1 $i) }}
      protocol: TCP
      port: {{ add $start $i }}
      targetPort: {{ add $start $i }}
  {{- end }}
  # Otherwise, use the standard proxyPort helm Chart variable
{{- else }}
    - name: node
      protocol: TCP
      port: {{ .Values.node.proxyPort }}
      targetPort: {{ .Values.node.proxyPort }}
{{- end }}
