apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgres-deployment
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
{{ include "store.labels" . | indent 4 }}
    component: postgres
spec:
  selector:
    matchLabels:
{{ include "store.matchLabels" . | indent 6 }}
      component: postgres
  template:
    metadata:
      labels:
{{ include "store.labels" . | indent 8 }}
        component: postgres
    spec:
      containers:
      - name: store-postgres
        image: "{{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}"
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: {{ .Values.database.name }}
        - name: POSTGRES_USER
          value: {{ .Values.database.username }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.database.password }}
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
          subPath: postgres
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-postgres-pvc