apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-vantage6-postgres-pv
  namespace: {{ .Release.Namespace | quote }}
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: {{ .Values.database.volumePath }}