apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rabbitmq-service
  namespace: {{ .Release.Namespace | quote }}
spec:
  selector:
{{ include "vantage6.matchLabels" . | indent 4 }}
    component: rabbitmq
  ports:
    - port: 5672
      targetPort: 5672