name: Test Client Script

on:
  pull_request:

jobs:
  test-client-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        make install-dev

    - name: Run client script test
      run: |
        v6 test client-script --create-dev-network -n test --server-url http://172.17.0.1