apiVersion: v2
name: node
description: A Helm chart to deploy a vantage6 node
type: application
version: "5.0.0-b4"
appVersion: "5.0.0-b4"
dependencies:
  - name: common
    version: "5.0.0-b4"
    repository: file://../common
